import { type VFC, useEffect, useState } from 'react';
import { useDispatch } from 'react-redux';

import { Field, Form, type FormikContextType, FormikProvider, useFormik } from 'formik';
import { c } from 'ttag';
import uniqid from 'uniqid';

import { Button } from '@proton/atoms';
import { DropdownMenuButton, Icon } from '@proton/components';
import { itemCreationIntent } from '@proton/pass/store';
import { isEmptyString } from '@proton/pass/utils/string';
import { getEpoch } from '@proton/pass/utils/time/get-epoch';
import { omit } from '@proton/shared/lib/helpers/object';

import { ItemNewProps } from '../../../../shared/items';
import { deriveAliasPrefixFromName } from '../../../../shared/items/alias';
import { FieldsetCluster } from '../../../components/Controls/FieldsetCluster';
import { QuickActionsDropdown } from '../../../components/Dropdown/QuickActionsDropdown';
import { PasswordFieldWIP } from '../../../components/Fields/PasswordField';
import { TextFieldWIP } from '../../../components/Fields/TextField';
import { TextAreaFieldWIP } from '../../../components/Fields/TextareaField';
import { TitleField } from '../../../components/Fields/TitleField';
import { UrlGroupFieldCluster, createNewUrl } from '../../../components/Fields/UrlGroupFieldCluster';
import { ItemCreatePanel } from '../../../components/Panel/ItemCreatePanel';
import { usePopupContext } from '../../../context';
import { AliasModal } from '../Alias/Alias.modal';
import { type LoginItemFormValues, NewLoginItemFormValues, validateNewLoginForm } from './Login.validation';

const FORM_ID = 'new-login';

export const LoginNew: VFC<ItemNewProps<'login'>> = ({ shareId, onSubmit, onCancel }) => {
    const dispatch = useDispatch();
    const { realm, subdomain } = usePopupContext();
    const isValidURL = realm !== undefined;
    const url = subdomain !== undefined ? subdomain : realm;
    const defaultName = isValidURL ? url! : '';

    const [aliasModalOpen, setAliasModalOpen] = useState(false);

    const initialValues: LoginItemFormValues<false> = {
        name: defaultName,
        shareId,
        username: '',
        password: '',
        note: '',
        totpUri: '',
        url: isValidURL ? createNewUrl(url!).url : '',
        urls: [],
        withAlias: false,
    };

    const form = useFormik<NewLoginItemFormValues>({
        initialValues,
        initialErrors: validateNewLoginForm(initialValues),
        onSubmit: ({ name, note, username, password, shareId, url, urls, ...values }) => {
            const createTime = getEpoch();
            const optimisticId = uniqid();

            const withAlias =
                values.withAlias &&
                values.aliasSuffix !== undefined &&
                values.aliasPrefix !== undefined &&
                values.mailboxes.length > 0;

            if (withAlias) {
                const aliasOptimisticId = uniqid();

                dispatch(
                    itemCreationIntent({
                        type: 'alias',
                        optimisticId: aliasOptimisticId,
                        shareId,
                        createTime: createTime - 1 /* alias will be created before login in saga */,
                        metadata: {
                            name: `Alias for ${name}`,
                            note: '',
                            itemUuid: aliasOptimisticId,
                        },
                        content: {},
                        extraData: {
                            mailboxes: values.mailboxes,
                            prefix: values.aliasPrefix!,
                            signedSuffix: values.aliasSuffix!.signature,
                            aliasEmail: username,
                        },
                        extraFields: [],
                    })
                );
            }

            onSubmit({
                type: 'login',
                optimisticId,
                shareId,
                createTime,
                metadata: {
                    name,
                    note,
                    itemUuid: optimisticId,
                },
                content: {
                    username,
                    password,
                    urls: Array.from(new Set(urls.map(({ url }) => url).concat(isEmptyString(url) ? [] : [url]))),
                    totpUri: '',
                },
                extraFields: [],
            });
        },
        validate: validateNewLoginForm,
        validateOnChange: true,
    });

    const { values, touched, setFieldValue } = form;

    useEffect(() => {
        async function fillAutoGeneratedAlias() {
            if ('aliasPrefix' in touched && !touched.aliasPrefix && values.name) {
                try {
                    await setFieldValue('aliasPrefix', deriveAliasPrefixFromName(values.name), true);
                } catch (_) {}
            }
        }

        void fillAutoGeneratedAlias();
    }, [values.name, 'aliasPrefix' in touched && !touched.aliasPrefix, setFieldValue]);

    const valid = form.isValid;

    return (
        <>
            <ItemCreatePanel type="login" formId={FORM_ID} valid={valid} handleCancelClick={onCancel}>
                <FormikProvider value={form}>
                    <Form id={FORM_ID}>
                        <FieldsetCluster>
                            <Field
                                name="name"
                                label={c('Label').t`Title`}
                                placeholder={c('Placeholder').t`Untitled`}
                                autoFocus
                                component={TitleField}
                            />
                        </FieldsetCluster>

                        <FieldsetCluster>
                            <Field
                                name="username"
                                label={c('Label').t`Username`}
                                placeholder={c('Placeholder').t`Enter email or username`}
                                component={TextFieldWIP}
                                itemType="login"
                                icon="user"
                                {...(form.values.withAlias
                                    ? {
                                          actions: (
                                              <QuickActionsDropdown>
                                                  <DropdownMenuButton
                                                      className="flex flex-align-items-center text-left"
                                                      onClick={() => {
                                                          void form.setValues(
                                                              (values) =>
                                                                  ({
                                                                      ...omit(values as LoginItemFormValues<true>, [
                                                                          'aliasPrefix',
                                                                          'aliasSuffix',
                                                                          'mailboxes',
                                                                      ]),
                                                                      withAlias: false,
                                                                      username: initialValues.username,
                                                                  } as LoginItemFormValues<false>)
                                                          );
                                                      }}
                                                  >
                                                      <Icon name="trash" className="mr0-5" />
                                                      {c('Action').t`Delete alias`}
                                                  </DropdownMenuButton>
                                              </QuickActionsDropdown>
                                          ),
                                      }
                                    : {
                                          actions: (
                                              <Button
                                                  icon
                                                  pill
                                                  color="weak"
                                                  shape="solid"
                                                  size="small"
                                                  className="pass-item-icon"
                                                  title={c('Action').t`Generate alias`}
                                                  onClick={async () => {
                                                      try {
                                                          await form.setValues(
                                                              (values) =>
                                                                  ({
                                                                      ...values,
                                                                      withAlias: true,
                                                                      aliasPrefix: '',
                                                                      aliasSuffix: undefined,
                                                                      mailboxes: [],
                                                                  } as LoginItemFormValues<true>)
                                                          );
                                                          await form.setFieldTouched('aliasPrefix', false);
                                                      } catch (_) {}
                                                      setAliasModalOpen(true);
                                                  }}
                                              >
                                                  <Icon name="alias" size={24} />
                                              </Button>
                                          ),
                                      })}
                            />
                            <Field
                                name="password"
                                label={c('Label').t`Password`}
                                placeholder={c('Placeholder').t`Enter password`}
                                icon="key"
                                component={PasswordFieldWIP}
                            />
                        </FieldsetCluster>

                        <UrlGroupFieldCluster form={form} />

                        <FieldsetCluster>
                            <Field
                                name="note"
                                label={c('Label').t`Note`}
                                placeholder={c('Placeholder').t`Enter a note ...`}
                                component={TextAreaFieldWIP}
                                icon="note"
                            />
                        </FieldsetCluster>
                    </Form>
                </FormikProvider>
            </ItemCreatePanel>

            {aliasModalOpen && (
                <AliasModal<LoginItemFormValues<true>>
                    open={aliasModalOpen}
                    onClose={async () => {
                        try {
                            await form.setFieldTouched('aliasPrefix', undefined);
                            await form.setValues(
                                (values) =>
                                    ({
                                        ...omit(values as LoginItemFormValues<true>, [
                                            'aliasPrefix',
                                            'aliasSuffix',
                                            'mailboxes',
                                        ]),
                                        withAlias: false,
                                    } as LoginItemFormValues<false>)
                            );
                        } catch (_) {}
                        setAliasModalOpen(false);
                    }}
                    handleSubmitClick={async () => {
                        try {
                            await form.setFieldTouched('aliasPrefix', true);
                            await form.setValues((values) => {
                                const valuesWithAlias = values as LoginItemFormValues<true>;

                                return {
                                    ...values,
                                    username: valuesWithAlias.aliasPrefix! + valuesWithAlias.aliasSuffix!.value,
                                };
                            });
                        } catch (_) {}
                        setAliasModalOpen(false);
                    }}
                    form={form as FormikContextType<LoginItemFormValues<true>>}
                    shareId={shareId}
                />
            )}
        </>
    );
};
